{{
    config(
        materialized = 'table'
    )
}}

WITH HOUR_FOR_PAYMENT_2020 AS (
    SELECT
        MAX(CASE WHEN YEAR = '2020' THEN HOUR_FOR_PAYMENT END) AS HOUR_FOR_PAYMENT_2020
    FROM {{ ref('int_mhi_mhp_5') }}
)

SELECT 
    YEAR,
    m.HOUR_FOR_PAYMENT,
    (HOUR_FOR_PAYMENT_2020.HOUR_FOR_PAYMENT_2020 - m.HOUR_FOR_PAYMENT) AS HOUR_DIFFERENCE_SUBTRACTION,
    ROUND((HOUR_FOR_PAYMENT_2020.HOUR_FOR_PAYMENT_2020 / m.HOUR_FOR_PAYMENT), 2) AS HOUR_DIFFERENCE_PERCENTAGE
FROM {{ ref('int_mhi_mhp_5') }} m
CROSS JOIN HOUR_FOR_PAYMENT_2020;


