with MHI AS (

SELECT 
    _ROW AS MHI_ID, 
    MEDIAN_HOUSEHOLD_INCOME_IN_THE_US AS MHI,
    SUBSTRING(YEAR, 1, 4) AS MHI_BY_YEAR
FROM PC_FIVETRAN_DB.MEDIAN_HOUSEHOLD_INCOME_BY_YEAR.MEDIAN_HOUSEHOLD_INCOME
)

SELECT * FROM MHI