SELECT
    CAST(_ROW AS int) AS ID_MW,
    SUBSTRING(YEAR, 1, 4) AS MW_BY_YEAR,
    FEDERAL_MINIMUM_WAGE
FROM {{ source('GOOGLE_SHEETS_FED_MIN_WAGE', 'FEDERAL_MINIMUM_WAGE') }}
ORDER BY MW_BY_YEAR