
WITH MHP AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY SUBSTRING(DATE, 1, 4)) AS MHP_ID,
        SUBSTRING(DATE, 1, 4) AS MHP_BY_YEAR, 
        FLOOR(SUM(MEDIAN_SALE_PRICE_OF_HOUSES_IN_THE_US)) AS TotalPrice
    FROM {{ source('HOUSE_PRICE','MEDIAN_SALE_PRICES') }}
    GROUP BY MHP_BY_YEAR
)

SELECT
    MHP_ID,
    MHP_BY_YEAR,
    TotalPrice / 4 AS MHP
FROM MHP









